on:
  push:
    
jobs:
  test-application:
    runs-on: [self-hosted, linux, x64]
    name: "Testing phase"
    
    steps:
     - name: "Checkout source code"
       uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
        python-version: "3.10"

     - run: |
        echo:"Hello from the runner!"
    
