semgrep:
  name: Semgrep
  runs-on: ubuntu-latest
  container: # Use a container
    image:returntocorp/semgrep:1.1.0  if: (github.actor != 'dependabot[bot]')
  steps:
  - name: "Checkout source"
    uses: actions/checkout@v3

  - name: "Execute semgrep" 
    run: semgrep ci  --sarif  --output semgrep.sarif
    env:
      SEMGREP_RULES: p/default
  
  - name: "Upload SARIF file for GitHub CodeQL"
  uses: github/codeql-action/upload-sarif@v2
  if: always()
  with:
         sarif_file: semgrep.sarif
    
